#!/usr/bin/env bash
# commands to install nginx on my web server

sudo apt-get update
sudo apt-get install nginx
sudo ufw 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

# testing nginx
sudo nginx -t

sudo service nginx reload
