#!/usr/bin/env bash
# configuration of the nginx to listen to port 80

# remove the default nginx configuration file
rm /etc/nginx/sites-enabled/default

# configure nginx to listen to port 80
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# restart the nginx
sudo service nginx restart
