#!/user/bin/env bash
# fix a web server to run Nginx as the nginx user listening ton port 8080
sed -i "s/#user www-data/user nginx/"/etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-avaliable/default
chmod 644 /etc/nginx.conf
pkill apache2
sudo -u nginx service nginx start
